// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Rediter.Api.Data;

#nullable disable

namespace Rediter.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260508225408_AddDescriptionInUser")]
    partial class AddDescriptionInUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rediter.Api.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FILE_NAME");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MIME_TYPE");

                    b.Property<int>("Size")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FILE_SIZE_BYTES");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STORAGE_PATH");

                    b.HasKey("Id");

                    b.ToTable("PICTURES");
                });

            modelBuilder.Entity("Rediter.Api.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("Content")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("LocationName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LOCATION_NAME");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("POSTS");
                });

            modelBuilder.Entity("Rediter.Api.Models.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DISPLAY_ORDER");

                    b.Property<int>("PictureId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PICTURE_ID");

                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("POST_ID");

                    b.HasKey("Id");

                    b.HasIndex("PictureId");

                    b.HasIndex("PostId");

                    b.ToTable("POST_IMAGES");
                });

            modelBuilder.Entity("Rediter.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_VERIFIED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORD");

                    b.Property<int?>("ProfileCoverId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PROFILE_COVER_ID");

                    b.Property<int?>("ProfilePictureId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PROFILE_PICTURE_ID");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REFRESH_TOKEN");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REFRESH_TOKEN_EXPIRATION");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFICATION_CODE");

                    b.HasKey("Id");

                    b.HasIndex("ProfileCoverId");

                    b.HasIndex("ProfilePictureId");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Rediter.Api.Models.Post", b =>
                {
                    b.HasOne("Rediter.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rediter.Api.Models.PostImage", b =>
                {
                    b.HasOne("Rediter.Api.Models.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rediter.Api.Models.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Rediter.Api.Models.User", b =>
                {
                    b.HasOne("Rediter.Api.Models.Picture", "ProfileCover")
                        .WithMany()
                        .HasForeignKey("ProfileCoverId");

                    b.HasOne("Rediter.Api.Models.Picture", "ProfilePicture")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId");

                    b.Navigation("ProfileCover");

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("Rediter.Api.Models.Post", b =>
                {
                    b.Navigation("PostImages");
                });
#pragma warning restore 612, 618
        }
    }
}
